### ISSUE TITLE
Question: Parsing JSON with arbitrary structure?

### ISSUE THREAD

**Issue by kmatt** [treeform/jsony#13]
Looking for a faster approach to walking nested JSON data with an arbitrary structure. The stdlib json library is a bit slow. Can jsony be used to walk nested JSON data without specifying a type? 

This won't work without also importing `json`, and I'm not sure if that is the correct approach in Nim:

```
import jsony
let s = readFile("test.json")
let js = s.fromJson()

for j in js:
  echo j
```

**Comment by treeform** [comment]
Yes that is the correct appraoch.

Parsing JSON with arbitrary structure into `JsonNode`s is slower than parsing json directly into objects because you need to create the intermediate nodes and that takes a lot of time.

When `jsony` parses arbitrary json into JsonNode it uses the `json` module's nodes. So you need to import `json` to work with them. It does it slightly faster than regular `json` parser but the main speedup of `jsony` is to skip those nodes all together.
